Socio/chat/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'chat'

urlpatterns = [
    path('chat/',views.ChatRooms.as_view(),name='chatRooms'),
    path('chat/<pk>',views.chats,name='chats'),
    path('chat/<pk>/location/<id>',views.location,name='location'),
    path('save_message/', views.save_message, name='chat_save_message'),
    path('share_location/', views.share_location, name='chat_share_location'),
]

Socio/groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('groups', views.GroupListView.as_view(), name="groupList"),
    path('groups/create', views.CreateGroupView.as_view(), name="createGroup"),
    path('groups/edit/<pk>', views.UpdateGroupView.as_view(), name="updateGroup"),
    path('groups/delete/<pk>', views.DeleteGroupView.as_view(), name="deleteGroup"),
    path('groups/leave/<pk>', views.leaveGroup, name="leaveGroup"),
    path('groups/members/<pk>', views.addMember, name="members"),
    path('groups/add-member/<pk>', views.AddMemberView.as_view(), name="addMember"),
    path('groups/add-admin/<pk>', views.AddAdminView.as_view(), name="addAdmin"),
    path('groups/<name>',views.GroupView.as_view(),name="groupDetail"),
    path('groups/createPost/<pk>',views.CreatePost.as_view(),name="createPost"),


]

Socio/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('all/profile',views.AllProfilesView.as_view(), name="allProfiles"),
    path('profile/friends', views.friendList, name="friendList"),
    path('profile/friends/<pk>', views.removeFriend, name="removeFriend"),
    path('profile/<username>', views.ProfileView.as_view(), name="profileView"),
    path('profile/edit/<pk>', views.UpdateProfileView.as_view(), name="editProfile"),
    path('profile/create/<pk>', views.CreateProfileView.as_view(), name="createProfile"),

]

Socio/socio/urls.py
from django.contrib import admin
from django.urls import path,include
from posts import views

app_name = 'socio'

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('socio.urls')),
    path('', include('accounts.urls')),
    path('', include('profiles.urls')),
    path('', include('message.urls')),
    path('', include('requests.urls')),
    path('', include('posts.urls')),
    path('', include('chat.urls')),
    path('', include('groups.urls')),
    path('',views.postsView,name='home'),


]

Socio/groups/models.py
from django.db import models
from django.conf import settings
User=settings.AUTH_USER_MODEL

# Create your models here.
class Group(models.Model):
    admin = models.ManyToManyField(User, related_name="group_admin")
    name = models.CharField("Name", max_length=20, unique=True)
    info = models.CharField("Short Info", max_length=200, blank=True, null=True)
    picture = models.ImageField('Group picture', upload_to='static/profile_pics/%Y-%m-%d/', null=True, blank=True)
    members = models.ManyToManyField(User, related_name="group_member")

    def __str__(self):
        return str(self.name)

Socio/groups/views.py
from django.views import generic
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions
from .models import *
from profiles.models import *
from chat.models import *
from posts.models import *
# Create your views here.


User = get_user_model()

class CreateGroupView(LoginRequiredMixin, generic.CreateView):
    login_url = '/login'
    model = Group
    fields = ['name', 'info', 'picture']

    def form_valid(self, form):
        user=self.request.user
        if form.is_valid():
            form.save()
            form.instance.admin.add(user)
            form.instance.members.add(user)
            chat = ChatRoom()
            chat.eid = form.instance.name
            chat.group = form.instance
            chat.save()
            chat.members.add(user)

            return redirect('groups:groupDetail',form.instance.name)

class UpdateGroupView(LoginRequiredMixin, generic.UpdateView):
    login_url = '/login'
    model = Group
    fields = ['name', 'info', 'picture']

    def dispatch(self, request, *args, **kwargs):
        user=self.request.user
        group=Group.objects.get(pk=self.kwargs['pk'])
        if user not in group.admin.all():
            return redirect('home')
        else:
            if request.method.lower() in self.http_method_names:
                handler = getattr(self, request.method.lower(), self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed
            return handler(request, *args, **kwargs)


    def form_valid(self, form):
        if form.is_valid():
            form.save()
            return redirect('groups:groupDetail',form.instance.name)



class GroupView(LoginRequiredMixin, generic.DetailView):
    login_url = '/login'
    template_name='groups/group_view.html'
    context_object_name = 'context'

    def get_object(self, queryset=Profile.objects):
        group=Group.objects.get(name=self.kwargs['name'])
        member=False
        admin=False
        all_posts=group.post_set.all()
        if self.request.user in group.admin.all():
            admin = True
        if self.request.user in group.members.all():
            member = True
        members=group.members.count()
        return {'group': group,'admin': admin, 'member': member, 'all_posts': all_posts,'members':members }

@login_required(login_url='/login')
def addMember(request,pk):
    group = Group.objects.get(pk=pk)
    if request.user not in group.admin.all():
        return redirect('home')
    return render(request,'groups/members.html',{'group':group})

class AddMemberView(LoginRequiredMixin, APIView):
    login_url =  '/login'
    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, pk, format=None):
        group=Group.objects.get(pk=pk)
        friend=User.objects.get(username=request.GET['friend'])

        if friend in group.members.all():
            group.members.remove(friend)
            group.chatroom.members.remove(friend)
            group.admin.remove(friend)
            status='removed'
        else:
            group.members.add(friend)
            group.chatroom.members.add(friend)
            status='added'

        data = {
            'status':status
        }
        return Response(data)

class AddAdminView(LoginRequiredMixin, APIView):
    login_url =  '/login'
    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, pk, format=None):
        group=Group.objects.get(pk=pk)
        friend=User.objects.get(username=request.GET['friend'])

        if friend in group.admin.all():
            group.admin.remove(friend)
            status='removed'
        else:
            group.admin.add(friend)
            status='added'

        data = {
            'status':status
        }
        return Response(data)


class GroupListView(LoginRequiredMixin, generic.ListView):
    login_url = '/login'
    template_name = 'groups/group_list.html'
    context_object_name = 'all_groups'


    def get_queryset(self):
        q = self.request.user.group_member.all()
        return q

class DeleteGroupView(LoginRequiredMixin,generic.DeleteView):
    login_url = '/login'
    model = Group
    success_url = reverse_lazy('groups:groupList')

    def delete(self, request, *args, **kwargs):
        group = Group.objects.get(pk=kwargs['pk'])
        if self.request.user not in group.admin.all():
            return redirect('home')

        self.object = self.get_object()
        self.object.delete()
        return HttpResponseRedirect(self.get_success_url())

@login_required(login_url='/login')
def leaveGroup(request,pk):
    group=Group.objects.get(pk=pk)
    if request.user not in group.members.all():
        return redirect('home')
    group.members.remove(request.user)
    group.chatroom.members.remove(request.user)
    if group.members.count() == 0:
        group.delete()
    elif request.user in group.admin.all():
        group.admin.remove(request.user)
        if group.admin.count() == 0:
            group.admin.add(group.members.all()[0])

    return redirect('home')

class CreatePost(LoginRequiredMixin,CreateView):
    login_url = '/login'
    model=Post
    fields = ['title','text','image','file']

    def dispatch(self, request, *args, **kwargs):
        if request.user not in Group.objects.get(pk=self.kwargs['pk']).members.all():
            return redirect('home')

        if request.method.lower() in self.http_method_names:
            handler = getattr(self, request.method.lower(), self.http_method_not_allowed)
        else:
            handler = self.http_method_not_allowed
        return handler(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.group = Group.objects.get(pk=self.kwargs['pk'])
        if form.is_valid():
            form.save()
            return redirect('home')

Socio/templates/groups/group_confirm_delete.html
{% extends "base.html" %}
{% load staticfiles %}

{% block body %}
    .
  <div class="container">
    <div class="row">
      <div class="col-sm-12">

        <div class="alert alert-danger">
            Are you sure you want to delete this group?
        </div>

        <p>{{ group.name }}</p>

        <form action="" method="post">
          {% csrf_token %}
          <input type="submit" value="Confirm Delete" class="btn btn-danger" />
        </form>

      </div>
    </div>
  </div>
{% endblock %}

Socio/templates/groups/group_form.html
{%  extends 'base.html' %}
{% load staticfiles %}

{% load thumbnail %}

{%  block body %}

    <div class="post-project">
            <h3>Create a Group</h3>
            <div class="post-project-fields">
                <form action="" method="post" enctype="multipart/form-data" style="margin-left: 25%;">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="row container">
{#                            <div class="col-sm-offset-2 col-sm-8">#}
{#                                <span class="text-danger small">{{ field.errors }}</span>#}
{#                            </div>#}
                            <label class="control-label col-sm-2 " for="title">{{ field.label_tag }}</label>
                            <div class="col-sm-4">{{ field }}</div>
                            <br>
                        </div>
                    {% endfor %}
                <div>
                    <ul style="margin-left: 12.5%;">
                        <li><button class="active" type="submit" value="post">Create</button></li>
                        <li><a href="{% url 'home' %}" title="">Cancel</a></li>
                    </ul>
                </div>
                </form>
            </div><!--post-project-fields end-->
        </div><!--post-project end-->
{% endblock %}

Socio/templates/groups/group_list.html
{%  extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block body %}
    <section class="companies-info">
			<div class="container">
				<div class="company-title">
					<h3>All Groups
                    <a style="float: right;" href="{% url 'groups:createGroup' %}"><button class="btn-sm btn-primary">New Group</button> </a>
                    </h3>
				</div><!--company-title end-->
				<div class="companies-list">
					<div class="row">
                    {%  for profile in all_groups %}
						<div class="col-lg-3 col-md-4 col-sm-6 col-12">
							<div class="company_profile_info">
								<div class="company-up-info">
                                    <img src="../{{ profile.picture }}" width="100px" height="100px" alt="">
                                    <h3>{{ profile.name }}</h3>
									<h4>{{ profile.info }}</h4>
								    <a href="{% url 'groups:groupDetail' profile %}" title="" class="view-more-pro">View Group</a>

								</div>

							</div><!--company_profile_info end-->
						</div>
                    {% endfor %}
                    </div>
				</div><!--companies-list end-->
				<div class="process-comm">
					<a href="#" title=""><img src="images/process-icon.png" alt=""></a>
				</div>
			</div>
		</section><!--companies-info end-->

{% endblock %}

Socio/templates/groups/group_view.html
{%  extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block title %}
    {{ context.user }}
{% endblock %}

{% block body %}


<main>
    <div class="main-section">
        <div class="container">
            <div class="main-section-data">
                <div class="row">
                    <div class="col-lg-3" style="margin-top: 10%;">
                        <div class="main-left-sidebar">
                            <div class="user_profile">
                                <div class="user-pro-img">
                                    <img src="../{% thumbnail context.group.picture 140x140 %}" alt="">
                                </div><!--user-pro-img end-->

                                <div class="user_pro_status">
                                {% if context.admin %}
                                    <ul class="flw-hr">
                                        <li><a href="{%  url 'groups:updateGroup' context.group.pk %}" title="" class="flww"> Edit Group</a></li>
                                        <li><a href="{% url 'groups:deleteGroup' context.group.pk %}" title="" class="hre">Delete Group</a></li>
                                    </ul>
                                {% endif %}
                                    <ul class="flw-status">
                                        <li>
                                            <span><a href="{% url 'groups:members' context.group.pk %}" title="" class="">Members</a></span>
                                            <b>{{ context.members }}</b>
                                        </li>
                                    </ul>

                                </div><!--user_pro_status end-->

                            </div><!--user_profile end-->
                        </div><!--main-left-sidebar end-->
                    </div>
                    <div class="col-lg-6">
                        <div class="main-ws-sec">
                            <div class="user-tab-sec post-topbar">
                                <h3>{{ context.group.name }}</h3>
                                <div class="star-descp user-picy">
                                    <span>{{ context.group.info }}</span>
                                </div><!--star-descp end-->
                                <div class="post-st">
                                    <ul>
                                        <li><a class="" href="{% url 'groups:createPost' context.group.pk %}" title="">Create a Post</a></li>
                                    </ul>
                                </div>
                            </div><!--user-tab-sec end-->
                            <div class="product-feed-tab current" id="feed-dd">
                                <div class="posts-section">
                                    {% include "posts/post.html" %}
                                </div><!--posts-section end-->
                            </div><!--product-feed-tab end-->
                        </div><!--main-ws-sec end-->
                    </div>
                    <div class="col-lg-3">
                        <div class="right-sidebar">
                            <div class="widget widget-jobs">
                                <div class="sd-title">
                                    <h3>Members</h3>
                                </div>
                                <div class="jobs-list">
                                    <ul>
                                        {% for member in context.group.members.all %}
                                            <li>
                                            <div class="usy-dt">
                                                <img src="../{{ member.profile.picture }}" width="40" height="40">
                                                <div class="usy-name">
                                                <p><a href="{% url 'profiles:profileView' member %}">
                                                    {{ member.profile.firstName }} {{ member.profile.lastName }}
                                                </a></p>
                                                </div>
                                            </div>
                                            </li></br>
                                        {% endfor %}
                                    </ul>
                                </div><!--jobs-list end-->
                            </div><!--widget-jobs end-->

                        </div><!--right-sidebar end-->
                    </div>
                </div>
            </div><!-- main-section-data end-->
        </div>
    </div>
</main>


{% endblock %}

Socio/templates/groups/group_view1.html
{%  extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block title %}
    {{ context.user }}
{% endblock %}

{% block body %}
    <div class="container ">
        <img src="../{% thumbnail context.group.picture 140x140 %}" width="200" height="200"><br>
        <h1>{{ context.group.name }}</h1>
        <p>{{ context.group.info }}</p>

        {% if context.admin %}
            <a href="{%  url 'groups:updateGroup' context.group.pk %}"><button class="btn-primary btn-sm ">Edit Group</button></a>
            <a href="{% url 'groups:deleteGroup' context.group.pk %}"><button class="btn-primary btn-sm ">Delete Group</button></a><br>
            <a href="{% url 'groups:members' context.group.pk %}"><button class="btn-info">Add/Remove Members</button></a>
        {% endif %}

        {% if context.member %}
            <a href="{% url 'groups:leaveGroup' context.group.pk %}" class="float-right"><button class="btn-primary">Leave Group</button></a><br>
        {% endif %}

        <ul><h3>All Members</h3>
        {%  for member in context.group.members.all %}
            {% if member != request.user %}
                <li><a href="{% url 'profiles:profileView' member %}"><img src="../{% thumbnail member.profile.picture 140x140 %}" width="50" height="50">
                {{ member.profile.firstName }} {{ member.profile.lastName }}
            </a></li>
            {% endif %}

        {%  endfor %}
        </ul>

        {% if context.member %}
            <a href="{% url 'groups:createPost' context.group.pk %}"><button class="btn-primary">Create a Post</button></a>
        {% endif %}

        <div>
        <h3>{{ context.group.name }}'s Posts</h3>
            {% include "posts/post.html" %}
        </div>


    </div>


<script>
$('.groups').addClass('active');
</script>

{% endblock %}

{% block extra-head %}

{% endblock %}

Socio/templates/groups/members.html
{%  extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block body %}
    <div class="container">
        <a href="{% url 'groups:groupDetail' group.name %}"><button class="btn btn-info">Group Page</button> </a>
    <h2>Here are your Friends</h2>
    <section class="companies-info">
			<div class="container">
				<div class="company-title">
					<h3>All Friends</h3>
				</div><!--company-title end-->
				<div class="companies-list">
					<div class="row">
                    {%  for friend in request.user.profile.friends.all %}
						<div class="col-lg-3 col-md-4 col-sm-6 col-12">
							<div class="company_profile_info">
								<div class="company-up-info">
									<img src="/../{{ friend.profile.picture }}" width="100px" height="100px" alt="">
                                    <h3>{{ friend.profile.firstName }} {{ friend.profile.lastName }}</h3>
									<h4>{{ friend.profile.bio }}</h4>
                                    <button class="btn-sm btn-primary add-member follow" href="{% url 'groups:addMember' group.pk %}" friend="{{ friend }}">
                                        {% if friend in group.members.all %}
                                            Remove
                                        {% else %}
                                            Add
                                        {% endif %}
                                    </button>

                                    <button class="btn-sm btn-primary add-admin message-us {% if friend not in group.members.all %} hide {% endif %}" href="{% url 'groups:addAdmin' group.pk %}" friend="{{ friend }}">
                                        {% if friend in group.admin.all %}
                                            Remove Admin
                                        {% else %}
                                            Make Admin
                                        {% endif %}
                                    </button>
								</div>
                                <a href="{% url 'profiles:profileView' friend.profile.user %}" title="" class="view-more-pro">View Profile</a>
							</div><!--company_profile_info end-->
						</div>
                    {% endfor %}
                    </div>
				</div><!--companies-list end-->
				<div class="process-comm">
					<a href="#" title=""><img src="images/process-icon.png" alt=""></a>
				</div>
			</div>
		</section>
    </div>
    <script>
        $(document).ready(function () {
            $('.group').addClass('active');
            $('.add-member').click(function (e) {
                e.preventDefault();
                var Url = $(this).attr('href');
                var button = $(this);
                $.ajax({
                    url: Url,
                    method: "GET",
                    data: {
                        'friend': button.attr('friend'),
                    },
                    success: function (data) {
                        if(data.status == 'added'){
                            console.log(button.next());
                            button.next().removeClass("hide");
                            button.text('Remove');
                        }
                        else{
                            button.next().text("Make Admin");
                            button.next().addClass('hide');
                            button.text('Add');
                        }
                    }, error: function (error) {
                        alert(error);
                    }
                })
            });
            $('.add-admin').click(function (e) {
                e.preventDefault();
                var Url = $(this).attr('href');
                var button = $(this);
                $.ajax({
                    url: Url,
                    method: "GET",
                    data: {
                        'friend': button.attr('friend'),
                    },
                    success: function (data) {
                        if(data.status == 'added'){
                            button.text('Remove Admin');
                        }
                        else{
                            button.text('Make Admin');
                        }
                    }, error: function (error) {
                        alert(error);
                    }
                })
            });
        });
    </script>
{% endblock %}