Socio/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login"),
    path('createFace/', views.createFace, name="createFace"),
    path('createFaceEncoding/', views.createFaceEncoding, name="createFaceEncoding"),
    path('face/', views.face, name="face"),
    path('loginFace/', views.loginFace, name="uploadFace"),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('password-change/', views.PasswordChangeView.as_view(),name='password-change'),
]

Socio/chat/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'chat'

urlpatterns = [
    path('chat/',views.ChatRooms.as_view(),name='chatRooms'),
    path('chat/<pk>',views.chats,name='chats'),
    path('chat/<pk>/location/<id>',views.location,name='location'),
    path('save_message/', views.save_message, name='chat_save_message'),
    path('share_location/', views.share_location, name='chat_share_location'),
]

Socio/groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('groups', views.GroupListView.as_view(), name="groupList"),
    path('groups/create', views.CreateGroupView.as_view(), name="createGroup"),
    path('groups/edit/<pk>', views.UpdateGroupView.as_view(), name="updateGroup"),
    path('groups/delete/<pk>', views.DeleteGroupView.as_view(), name="deleteGroup"),
    path('groups/leave/<pk>', views.leaveGroup, name="leaveGroup"),
    path('groups/members/<pk>', views.addMember, name="members"),
    path('groups/add-member/<pk>', views.AddMemberView.as_view(), name="addMember"),
    path('groups/add-admin/<pk>', views.AddAdminView.as_view(), name="addAdmin"),
    path('groups/<name>',views.GroupView.as_view(),name="groupDetail"),
    path('groups/createPost/<pk>',views.CreatePost.as_view(),name="createPost"),


]

Socio/message/urls.py
from django.urls import path
from . import views

app_name = 'message'

urlpatterns = [
    path('message/create/<username>',views.CreateMessageView.as_view(), name="createMessage"),
    path('message',views.MessagesView.as_view(), name="messages"),
    path('generateSOS',views.SOS, name="generateSOS"),
    path('SOS',views.SOSView.as_view(), name="SOS"),
    path('SOS/location/<pk>', views.location, name='location'),
    path('files', views.FilesView.as_view(), name="files"),
    path('file/<username>',views.FileUploadView.as_view(), name="uploadFile"),
    path('download/<file_name>', views.downloadFile, name="download"),
    path('check/<file_name>', views.checkFile, name="check"),
]

Socio/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('all/profile',views.AllProfilesView.as_view(), name="allProfiles"),
    path('profile/friends', views.friendList, name="friendList"),
    path('profile/friends/<pk>', views.removeFriend, name="removeFriend"),
    path('profile/<username>', views.ProfileView.as_view(), name="profileView"),
    path('profile/edit/<pk>', views.UpdateProfileView.as_view(), name="editProfile"),
    path('profile/create/<pk>', views.CreateProfileView.as_view(), name="createProfile"),

]

Socio/requests/urls.py
from django.urls import path
from . import views

app_name = 'requests'

urlpatterns = [
    path('requests',views.FriendRequestView.as_view(), name="friendRequests"),
    path('request/<pk>',views.newFriendRequest, name="newFriendRequest"),
    path('request/accept/<pk>',views.acceptRequest, name="acceptRequest"),
    path('request/reject/<pk>',views.rejectRequest, name="rejectRequest"),

]

Socio/socio/urls.py
from django.contrib import admin
from django.urls import path,include
from posts import views

app_name = 'socio'

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('socio.urls')),
    path('', include('accounts.urls')),
    path('', include('profiles.urls')),
    path('', include('message.urls')),
    path('', include('requests.urls')),
    path('', include('posts.urls')),
    path('', include('chat.urls')),
    path('', include('groups.urls')),
    path('',views.postsView,name='home'),


]

Socio/message/models.py
from django.db import models
from django.conf import settings
from . import sha1
import os
User=settings.AUTH_USER_MODEL


# Create your models here.
class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE,related_name="message_sender")
    receiver = models.ForeignKey(User, on_delete=models.CASCADE,related_name="message_receiver")
    message = models.CharField(max_length=500)
    date = models.DateTimeField(auto_now=True, db_index=True)

class SOSMessage(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE,related_name="sos_sender")
    date = models.DateTimeField(auto_now=True, db_index=True)


class File(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE,related_name="file_sender")
    receiver = models.ForeignKey(User, on_delete=models.CASCADE,related_name="file_receiver")
    title = models.CharField(max_length=50)
    file = models.FileField(upload_to='message/uploads/')
    sha1 = models.CharField(max_length=20)
    date = models.DateTimeField(auto_now=True, db_index=True)

    def filepath(self):
        f=str(self.file)
        return f[16:]

    def getSha1(self):
        data = open(str(self.file), 'rb')
        sha = sha1.sha1(data)
        return sha

Socio/message/forms.py
from django import forms

class FileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

Socio/message/views.py
from django.views import generic
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from wsgiref.util import FileWrapper
from django.utils.encoding import smart_str
import mimetypes,os
from .models import *
from .forms import FileForm
# Create your views here.

User= get_user_model()

class CreateMessageView(LoginRequiredMixin,CreateView):
    login_url = '/login'
    model=Message
    fields = ['message']

    def dispatch(self, request, *args, **kwargs):
        sender = request.user
        receiver = User.objects.get(username=self.kwargs['username'])
        if not receiver in set(sender.profile.friends.all()):
            return redirect('home')
        else:
            if request.method.lower() in self.http_method_names:
                handler = getattr(self, request.method.lower(), self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed
            return handler(request, *args, **kwargs)

    def form_valid(self, form):
        sender = self.request.user
        receiver = User.objects.get(username=self.kwargs['username'])
        form.instance.sender = sender
        form.instance.receiver = receiver
        if form.is_valid():
            form.save()
            return redirect('home')

@login_required(login_url = "/login")
def SOS(request):
    sos = SOSMessage()
    sos.sender = request.user
    sos.save()
    return redirect('home')

@login_required(login_url='/login')
def location(request,pk):
    member = User.objects.get(pk=pk)
    context = {}
    context['member'] = member
    return render(request,"message/location.html",context)


class FileUploadView(LoginRequiredMixin,CreateView):
    login_url = '/login'
    model=File
    fields = ['title','file']

    def dispatch(self, request, *args, **kwargs):
        sender = request.user
        receiver = User.objects.get(username=self.kwargs['username'])
        if not receiver in set(sender.profile.friends.all()):
            return redirect('home')
        else:
            if request.method.lower() in self.http_method_names:
                handler = getattr(self, request.method.lower(), self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed
            return handler(request, *args, **kwargs)

    def form_valid(self, form):
        sender = self.request.user
        receiver = User.objects.get(username=self.kwargs['username'])
        form.instance.sender = sender
        form.instance.receiver = receiver

        if form.is_valid():
            form.save()
            file=File.objects.get(file=form.instance.file)
            file.sha1 = file.getSha1()
            file.save()
            return redirect('home')


class MessagesView(LoginRequiredMixin, generic.ListView):
    template_name='message/messages.html'
    context_object_name = 'all_messages'


    def get_queryset(self):
        user = User.objects.get(username=self.request.user)
        return reversed(user.message_receiver.all())


class SOSView(LoginRequiredMixin, generic.ListView):
    template_name = 'message/sos.html'
    context_object_name = 'all_messages'

    def get_queryset(self):
        user = User.objects.get(username=self.request.user)
        sos=[]
        for friend in user.profile.friends.all():
            for m in friend.sos_sender.all():
                sos.append(m)
        return sos

class FilesView(LoginRequiredMixin, generic.ListView):
    template_name='message/files.html'
    context_object_name = 'all_files'

    def get_queryset(self):
        user = User.objects.get(username=self.request.user)
        return reversed(user.file_receiver.all())

def downloadFile(request,file_name):
    file_path = 'message/uploads/'+file_name
    data = open(file_path, 'rb')
    sha = sha1.sha1(data)
    file = File.objects.get(file=file_path)
    context = {'file': file_name}
    if sha == file.sha1:
        file_wrapper = FileWrapper(open(file_path,'rb'))
        file_mimetype = mimetypes.guess_type(file_path)
        response = HttpResponse(file_wrapper, content_type=file_mimetype )
        response['X-Sendfile'] = file_path
        response['Content-Length'] = os.stat(file_path).st_size
        response['Content-Disposition'] = 'attachment; filename=%s/' % smart_str(file_name)
        return response
    else:
        context['msg'] = 'was Altered'

    return render(request, 'message/check.html', context)


def checkFile(request,file_name):
    file_path = 'message/uploads/'+file_name
    data = open(file_path,'rb')
    sha = sha1.sha1(data)
    file=File.objects.get(file=file_path)
    context = {
        'file' : file_name
    }
    if sha==file.sha1:
        context['msg'] = 'was Unaltered.'
    else:
        context['msg'] = 'was Altered'

    return render(request,'message/check.html',context)

Socio/templates/message/check.html
{%  extends 'base.html' %}
{% load staticfiles %}
{% block body %}
    <div class="container">
        <h1>{{ file }}  {{ msg }}</h1>
    </div>
{% endblock %}

Socio/templates/message/file_form.html
 {%  extends 'base.html' %}
{% load staticfiles %}

 {% block body %}
     <div class="post-project">
            <h3>Send a File</h3>
            <div class="post-project-fields">
                <form action="" method="post" enctype="multipart/form-data" style="margin-left: 25%;">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="row container">
{#                            <div class="col-sm-offset-2 col-sm-8">#}
{#                                <span class="text-danger small">{{ field.errors }}</span>#}
{#                            </div>#}
                            <label class="control-label col-sm-2 " for="title">{{ field.label_tag }}</label>
                            <div class="col-sm-4">{{ field }}</div>
                            <br>
                        </div>
                    {% endfor %}
                <div>
                    <ul style="margin-left: 12.5%;">
                        <li><button class="active" type="submit" value="post">Send</button></li>
                        <li><a href="{% url 'home' %}" title="">Cancel</a></li>
                    </ul>
                </div>
                </form>
            </div><!--post-project-fields end-->
        </div><!--post-project end-->

 {% endblock %}

Socio/templates/message/files.html
{%  extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block title %}
Messages
{% endblock %}
{% block extra-head %}
    <script>
        $(document).ready(function () {
            $('.file').addClass('active');
        })
    </script>
{% endblock %}
{% block body %}
    <div class="container">
    {% if all_files %}
        <div class="companies-list">
        <div class="row">
        {%  for r in all_files %}

            <div class="col-lg-3 col-md-4 col-sm-6 col-12">
                <div class="company_profile_info">
                    <div class="company-up-info">
                        <img src="../{{ r.sender.profile.picture }}" width="100px" height="100px" alt="">
                        <h3>{{ r.sender.profile.firstName }} {{ r.sender.profile.lastName }}</h3>
                        <p><img src="{% static 'images/clock.png' %}" alt="">{{ r.date }}</p>
                        <div style="border: solid">
                            <h3>
                                {{ r.title }}
                            </h3>

                        </div>
                        <ul>
                            <li><a href="{% url 'message:download' r.filepath %}" title="" class="follow">Download</a></li>
                            <li><a href="{% url 'message:createMessage' r.sender %}" title="" class="follow">Reply</a></li>
                        </ul>
                    </div>

                </div><!--company_profile_info end-->
            </div>
            {%  endfor %}
        </div>
        </div>
    {% else %}
        <h3>No Files</h3>
    {%  endif %}


{#    <div class="container">#}
{#    {% if all_files %}#}
{#        <ul>#}
{#            {%  for m in all_files %}#}
{#                <li><a href="{% url 'profiles:profileView' m.sender %}"><img src="../{% thumbnail m.sender.profile.picture 140x140 %}" width="50" height="50">#}
{#                    {{ m.sender.profile.firstName }} {{ m.sender.profile.lastName }}#}
{#                </a>#}
{#                <div class="container mdi-border">#}
{#                    <a href="{% url 'message:download' m.filepath %}"><p>{{ m.title }}</p></a>#}
{#                </div>#}
{#                <a href="{% url 'message:check' m.filepath %}"><button class="btn-primary">Check</button></a>#}
{#                <a href="{% url 'message:createMessage' m.sender %}"><button class="btn-primary">Reply</button> </a>#}
{#                <a href="{% url 'message:uploadFile' m.sender %}"><button class="btn-primary">Send a File</button> </a>#}
{#                </li>#}
{##}
{#            {%  endfor %}#}
{#        </ul>#}
{#    {% else %}#}
{#        <h3>No Files</h3>#}
{#    {%  endif %}#}
{#    </div>#}
{% endblock %}

Socio/templates/message/location.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <title>Geolocation</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/line-awesome.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/line-awesome-font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/slick.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/slick-theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}">
    <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'js/dateFormat.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.mCustomScrollbar.js' %}"></script>
    <script type="text/javascript" src="{% static 'lib/slick.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/scrollbar.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
  </head>
  <body>
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
        <header id="header">
        <div class="container">
            {% block navbar %}
            <div class="header-data">
                <div class="logo">
                    <a href="{% url 'home' %}" title=""><img src="{% static 'images/logo.png' %}" width="40px" height="40px" alt=""></a>
                </div><!--logo end-->
                <div class="search-bar">
                    <form  class="navbar-form navbar-left" role="search" method="get" action="{% url 'profiles:allProfiles' %}">
                        <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                        <button type="submit"><i class="la la-search"></i></button>
                    </form>
                </div><!--search-bar end-->
                <nav>
                    <ul>
                        <li class="home">
                            <a href="{% url 'home' %}" title="">
                                <span><img src="{% static 'images/icon1.png' %}" alt=""></span>
                                Home
                            </a>
                        </li>
                        <li class="profile">
                            <a href="{% url 'profiles:profileView' request.user %}" title="">
                                <span><img src="{% static 'images/icon3.png' %}" alt=""></span>
                                Profile
                            </a>
                        </li>
                        <li class="request">
                            <a href="{% url 'requests:friendRequests' %}" title="">
                                <span><img src="{% static 'images/icon4.png' %}" alt=""></span>
                                Friend Requests
                            </a>
                        </li>
                        <li class="message">
                            <a href="{% url 'message:messages' %}" title="" class="not-box-open">
                                <span><img src="{% static 'images/icon6.png' %}" alt=""></span>
                                Messages
                            </a>
                        </li>
                        <li class="file">
                            <a href="{% url 'message:files'  %}" title="">
                                <span><img src="{% static 'images/icon5.png' %}" alt=""></span>
                                Files
                            </a>
                        </li>
                        <li class="chat">
                            <a href="{% url 'chat:chatRooms'  %}" title="">
                                <span><img src="{% static 'images/chat.png' %}" width="20px" style="margin-top: -10%;" alt=""></span>
                                Chat
                            </a>
                        </li>
                        <li class="groups">
                            <a href="{% url 'groups:groupList' %}" title="">
                                <span><img src="{% static 'images/icon2.png' %}" alt=""></span>
                                Groups
                            </a>
                        </li>
                        <li class="generateSOS">
                            <a href="{% url 'message:generateSOS' %}" title="" class="not-box-open">
                                <span><img src="{% static 'images/icon7.png' %}" alt=""></span>
                                SOS
                            </a>
                        </li>
                        <li class="SOS">
                            <a href="{% url 'message:SOS' %}" title="" class="not-box-open">
                                <span><img src="{% static 'images/icon9.png' %}" alt=""></span>
                                View SOS
                            </a>
                        </li>
                    </ul>
                </nav><!--nav end-->
                <div class="menu-btn">
                    <a href="#" title=""><i class="fa fa-bars"></i></a>
                </div><!--menu-btn end-->


            </div><!--header-data end-->

        {% endblock %}
        </div>
    {% block logout %}
        {% if request.user != 'AnonymousUser' %}
        <a href="{% url 'accounts:logout' %}">
            <div class="nav navbar-nav navbar-right fa fa-sign-out" style="float: right; color: white ; border: 0px;   margin-top: 1%; font-size:24px;"> </div>
         </a>
        {% endif %}
    {% endblock %}
    </header><!--header end-->
.
    <div id="map"></div>
    <script>
      // Note: This example requires that you consent to location sharing when
      // prompted by your browser. If you see the error "The Geolocation service
      // failed.", it means you probably did not give permission for the browser to
      // locate you.
      var map, infoWindow;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -34.397, lng: 150.644},
          zoom: 6
        });
        infoWindow = new google.maps.InfoWindow;

        // Try HTML5 geolocation.
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var pos = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };

            infoWindow.setPosition(pos);
            infoWindow.setContent("{{ member }}");
            infoWindow.open(map);
            map.setCenter(pos);
          }, function() {
            handleLocationError(true, infoWindow, map.getCenter());
          });
        } else {
          // Browser doesn't support Geolocation
          handleLocationError(false, infoWindow, map.getCenter());
        }
      }

      function handleLocationError(browserHasGeolocation, infoWindow, pos) {
        infoWindow.setPosition(pos);
        infoWindow.setContent(browserHasGeolocation ?
                              'Error: The Geolocation service failed.' :
                              'Error: Your browser doesn\'t support geolocation.');
        infoWindow.open(map);
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCD1dTQZSGdJBuAmgbNt6QX1boH930n3CY&callback=initMap">
    </script>
  </body>
</html>

Socio/templates/message/message_form.html
 {%  extends 'base.html' %}
{% load staticfiles %}

{%  block body %}

    <div class="post-project">
            <h3>Send a Message</h3>
            <div class="post-project-fields">
                <form action="" method="post" enctype="multipart/form-data" style="margin-left: 25%;">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="row container">
{#                            <div class="col-sm-offset-2 col-sm-8">#}
{#                                <span class="text-danger small">{{ field.errors }}</span>#}
{#                            </div>#}
                            <label class="control-label col-sm-2 " for="title">{{ field.label_tag }}</label>
                            <div class="col-sm-4">{{ field }}</div>
                            <br>
                        </div>
                    {% endfor %}
                <div>
                    <ul style="margin-left: 12.5%;">
                        <li><button class="active" type="submit" value="post">Send</button></li>
                        <li><a href="{% url 'home' %}" title="">Cancel</a></li>
                    </ul>
                </div>
                </form>
            </div><!--post-project-fields end-->
        </div><!--post-project end--></form>
{% endblock %}

Socio/templates/message/messages.html
{%  extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block title %}
Messages
{% endblock %}
{% block extra-head %}
    <script>
        $(document).ready(function () {
            $('.message').addClass('active');
        })
    </script>
{% endblock %}
{% block body %}
    <div class="container">
    {% if all_messages %}
        <div class="companies-list">
        <div class="row">
        {%  for r in all_messages %}

            <div class="col-lg-3 col-md-4 col-sm-6 col-12">
                <div class="company_profile_info">
                    <div class="company-up-info">
                        <img src="../{{ r.sender.profile.picture }}" width="100px" height="100px" alt="">
                        <h3>{{ r.sender.profile.firstName }} {{ r.sender.profile.lastName }}</h3>
                        <p><img src="{% static 'images/clock.png' %}" alt="">{{ r.date }}</p>
                        <div style="border: solid">
                            <h3>
                                {{ r.message }}
                            </h3>
                        </div>
                        <ul>
                            <li><a href="{% url 'message:createMessage' r.sender %}" title="" class="follow">Reply</a></li>
                        </ul>
                    </div>

                </div><!--company_profile_info end-->
            </div>
            {%  endfor %}
        </div>
        </div>
    {% else %}
        <h3>No Messages</h3>
    {%  endif %}
    </div>
{% endblock %}

Socio/templates/message/sos.html
{%  extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block title %}
Messages
{% endblock %}
{% block extra-head %}
    <script>
        $(document).ready(function () {
            $('.message').addClass('active');
        })
    </script>
{% endblock %}
{% block body %}
    <div class="container">
    {% if all_messages %}
        <div class="companies-list">
        <div class="row">
        {%  for r in all_messages %}

            <div class="col-lg-3 col-md-4 col-sm-6 col-12">
                <div class="company_profile_info">
                    <div class="company-up-info">
                        <img src="../{{ r.sender.profile.picture }}" width="100px" height="100px" alt="">
                        <h3>{{ r.sender.profile.firstName }} {{ r.sender.profile.lastName }}</h3>
                        <p><img src="{% static 'images/clock.png' %}" alt="">{{ r.date }}</p>
                        <div style="border: solid">
                            <h3 style="color: red">
                                {{ r.sender }} is in an emergency
                            </h3>
                        </div>
                        <ul>
                            <li><a href="{% url 'message:location' r.sender.pk %}" title="" class="follow">Check Location</a></li>
                        </ul>
                    </div>

                </div><!--company_profile_info end-->
            </div>
            {%  endfor %}
        </div>
        </div>

    {% else %}
        <h3>No Messages</h3>
    {%  endif %}
    </div>
{% endblock %}