Socio/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login"),
    path('createFace/', views.createFace, name="createFace"),
    path('createFaceEncoding/', views.createFaceEncoding, name="createFaceEncoding"),
    path('face/', views.face, name="face"),
    path('loginFace/', views.loginFace, name="uploadFace"),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('password-change/', views.PasswordChangeView.as_view(),name='password-change'),
]

Socio/chat/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'chat'

urlpatterns = [
    path('chat/',views.ChatRooms.as_view(),name='chatRooms'),
    path('chat/<pk>',views.chats,name='chats'),
    path('chat/<pk>/location/<id>',views.location,name='location'),
    path('save_message/', views.save_message, name='chat_save_message'),
    path('share_location/', views.share_location, name='chat_share_location'),
]

Socio/groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('groups', views.GroupListView.as_view(), name="groupList"),
    path('groups/create', views.CreateGroupView.as_view(), name="createGroup"),
    path('groups/edit/<pk>', views.UpdateGroupView.as_view(), name="updateGroup"),
    path('groups/delete/<pk>', views.DeleteGroupView.as_view(), name="deleteGroup"),
    path('groups/leave/<pk>', views.leaveGroup, name="leaveGroup"),
    path('groups/members/<pk>', views.addMember, name="members"),
    path('groups/add-member/<pk>', views.AddMemberView.as_view(), name="addMember"),
    path('groups/add-admin/<pk>', views.AddAdminView.as_view(), name="addAdmin"),
    path('groups/<name>',views.GroupView.as_view(),name="groupDetail"),
    path('groups/createPost/<pk>',views.CreatePost.as_view(),name="createPost"),


]

Socio/message/urls.py
from django.urls import path
from . import views

app_name = 'message'

urlpatterns = [
    path('message/create/<username>',views.CreateMessageView.as_view(), name="createMessage"),
    path('message',views.MessagesView.as_view(), name="messages"),
    path('generateSOS',views.SOS, name="generateSOS"),
    path('SOS',views.SOSView.as_view(), name="SOS"),
    path('SOS/location/<pk>', views.location, name='location'),
    path('files', views.FilesView.as_view(), name="files"),
    path('file/<username>',views.FileUploadView.as_view(), name="uploadFile"),
    path('download/<file_name>', views.downloadFile, name="download"),
    path('check/<file_name>', views.checkFile, name="check"),
]

Socio/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('all/profile',views.AllProfilesView.as_view(), name="allProfiles"),
    path('profile/friends', views.friendList, name="friendList"),
    path('profile/friends/<pk>', views.removeFriend, name="removeFriend"),
    path('profile/<username>', views.ProfileView.as_view(), name="profileView"),
    path('profile/edit/<pk>', views.UpdateProfileView.as_view(), name="editProfile"),
    path('profile/create/<pk>', views.CreateProfileView.as_view(), name="createProfile"),

]

Socio/socio/urls.py
from django.contrib import admin
from django.urls import path,include
from posts import views

app_name = 'socio'

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('socio.urls')),
    path('', include('accounts.urls')),
    path('', include('profiles.urls')),
    path('', include('message.urls')),
    path('', include('requests.urls')),
    path('', include('posts.urls')),
    path('', include('chat.urls')),
    path('', include('groups.urls')),
    path('',views.postsView,name='home'),


]

Socio/templates/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
{% load staticfiles %}
{% load static %}
<title>{% block title %}Title{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="" />
<meta name="keywords" content="" />
<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/line-awesome.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/line-awesome-font-awesome.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'lib/slick.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'lib/slick-theme.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}">
<script src="{% static 'js/jquery-3.3.1.js' %}"></script>
<script src="{% static 'js/dateFormat.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.mCustomScrollbar.js' %}"></script>
<script type="text/javascript" src="{% static 'lib/slick.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/scrollbar.js' %}"></script>
<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
{% block extra-head %}
{% endblock %}
</head>


<body>
	

	<div class="wrapper">

    <header id="header">
        <div class="container">
            {% block navbar %}
            <div class="header-data">
                <div class="logo">
                    <a href="{% url 'home' %}" title=""><img src="{% static 'images/logo.jpeg' %}" width="40px" height="40px" alt=""></a>
                </div><!--logo end-->
                <div class="search-bar">
                    <form  class="navbar-form navbar-left" role="search" method="get" action="{% url 'profiles:allProfiles' %}">
                        <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                        <button type="submit"><i class="la la-search"></i></button>
                    </form>
                </div><!--search-bar end-->
                <nav>
                    <ul>
                        <li class="home">
                            <a href="{% url 'home' %}" title="">
                                <span><img src="{% static 'images/icon1.png' %}" alt=""></span>
                                Home
                            </a>
                        </li>
                        <li class="profile">
                            <a href="{% url 'profiles:profileView' request.user %}" title="">
                                <span><img src="{% static 'images/icon3.png' %}" alt=""></span>
                                Profile
                            </a>
                        </li>
                        <li class="request">
                            <a href="{% url 'requests:friendRequests' %}" title="">
                                <span><img src="{% static 'images/icon4.png' %}" alt=""></span>
                                Friend Requests
                            </a>
                        </li>
                        <li class="message">
                            <a href="{% url 'message:messages' %}" title="" class="not-box-open">
                                <span><img src="{% static 'images/icon6.png' %}" alt=""></span>
                                Messages
                            </a>
                        </li>
                        <li class="file">
                            <a href="{% url 'message:files'  %}" title="">
                                <span><img src="{% static 'images/icon5.png' %}" alt=""></span>
                                Files
                            </a>
                        </li>
                        <li class="chat">
                            <a href="{% url 'chat:chatRooms'  %}" title="">
                                <span><img src="{% static 'images/chat.png' %}" width="20px" style="margin-top: -10%;" alt=""></span>
                                Chat
                            </a>
                        </li>
                        <li class="groups">
                            <a href="{% url 'groups:groupList' %}" title="">
                                <span><img src="{% static 'images/icon2.png' %}" alt=""></span>
                                Groups
                            </a>
                        </li>
                        <li class="generateSOS">
                            <a href="{% url 'message:generateSOS' %}" title="" class="not-box-open">
                                <span><img src="{% static 'images/icon7.png' %}" alt=""></span>
                                SOS
                            </a>
                        </li>
                        <li class="SOS">
                            <a href="{% url 'message:SOS' %}" title="" class="not-box-open">
                                <span><img src="{% static 'images/icon9.png' %}" alt=""></span>
                                View SOS
                            </a>
                        </li>
                    </ul>
                </nav><!--nav end-->
                <div class="menu-btn">
                    <a href="#" title=""><i class="fa fa-bars"></i></a>
                </div><!--menu-btn end-->


            </div><!--header-data end-->

        {% endblock %}
        </div>
    {% block logout %}
        {% if request.user != 'AnonymousUser' %}
            <a href="{% url 'accounts:logout' %}">
                <div class="nav navbar-nav navbar-right fa fa-sign-out" style="float: right; color: white ; border: 0px;   margin-top: 1%; font-size:24px;"> </div>
             </a>
            {% if not request.user.face %}
                <a href="{% url 'accounts:createFace' %}">
                <div class="nav navbar-nav navbar-right fa fa-smile-o" style="float: right; color: white ; border: 0px;   margin-top: 1%; margin-right:1%; font-size:24px;"> </div>
                </a>
            {% endif %}

        {% endif %}
    {% endblock %}
    </header><!--header end-->

    {% block body %}

    {% endblock %}

	</div><!--theme-layout end-->

{% block map %}
{% endblock %}






</body>
</html>

Socio/templates/base1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    {% load static %}
    <title>{% block title %}Title{% endblock %}</title>
	<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
	<link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
	<link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
	<link href="{% static 'css/animate.css' %}" rel="stylesheet">
	<link href="{% static 'css/materialize.css' %}" rel="stylesheet">
    <link href="{% static 'css/a.css' %}" rel="stylesheet">

    <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'js/dateFormat.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/materialize.js' %}"></script>

    <style>
        body{
            background-color: #b8c6ff;
        }
    </style>
{% block extra-head %}
{% endblock %}
</head>
<body>
<header id="header">
    {% block navbar %}
    <nav class="navbar  navbar-collapse center-align navbar-static-top" style="background-color: midnightblue; height:11%;">
      <div class="container-fluid">
       <div class="navbar-header hide-on-large-only">
      <button type="button" class="navbar-toggle fa fa-sort-amount-asc" data-toggle="collapse" data-target="#myNavbar" ></button>
       </div>
       <div class="collapse navbar-collapse show-on-large" style="background-color: midnightblue " id="myNavbar">
        <ul class="nav navbar-nav">
            <li class="home"><a class="navbar-brand" href="{% url 'home' %}">Socio</a></li>
          <li class="profile"><a href="{% url 'profiles:profileView' request.user %}">Profile</a></li>
          <li class="request"><a href="{% url 'requests:friendRequests' %} ">Friend Requests</a></li>
          <li class="message"><a href="{% url 'message:messages' %}">Messages</a></li>
          <li class="file"><a href="{% url 'message:files'  %}">Files</a></li>
          <li class="chat"><a href="{% url 'chat:chatRooms' %}">Chat</a></li>
          <li class="groups"><a href="{% url 'groups:groupList' %}">Groups</a></li>
          <li class="generateSOS"><a href="{% url 'message:generateSOS' %}">SOS</a></li>
          <li class="SOS"><a href="{% url 'message:SOS' %}">View SOS</a></li>
            {% block extra-navbar %}
            {% endblock %}
        </ul>


        <form  style="margin-top: -5px; background-color:transparent;" class="navbar-form navbar-left" role="search" method="get" action="{% url 'profiles:allProfiles' %}">
            <div class="form-group">
                <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
            </div>
            <button type="submit" class="fa fa-search" style="background-color:transparent; border: 0px;"></button>
        </form>


       {% block logout %}
          {% if request.user != 'AnonymousUser' %}
          <a href="{% url 'accounts:logout' %}">
              <button class="nav navbar-nav navbar-right fa fa-sign-out" style="background-color:transparent; border: 0px;   margin-top: 1.5%; font-size:24px;"> </button>
          </a>
          {% endif %}
      {% endblock %}
        </div>
      </div>
    </nav>
    {% endblock %}

  </header>
  <!--/header-->


{% block body %}
{% endblock %}

</body>
</html>

Socio/templates/map.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <title>Geolocation</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/line-awesome.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/line-awesome-font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/slick.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/slick-theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}">
    <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'js/dateFormat.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.mCustomScrollbar.js' %}"></script>
    <script type="text/javascript" src="{% static 'lib/slick.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/scrollbar.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
  </head>
  <body>
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
        <header id="header">
        <div class="container">
            {% block navbar %}
            <div class="header-data">
                <div class="logo">
                    <a href="{% url 'home' %}" title=""><img src="{% static 'images/logo.png' %}" width="40px" height="40px" alt=""></a>
                </div><!--logo end-->
                <div class="search-bar">
                    <form  class="navbar-form navbar-left" role="search" method="get" action="{% url 'profiles:allProfiles' %}">
                        <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                        <button type="submit"><i class="la la-search"></i></button>
                    </form>
                </div><!--search-bar end-->
                <nav>
                    <ul>
                        <li class="home">
                            <a href="{% url 'home' %}" title="">
                                <span><img src="{% static 'images/icon1.png' %}" alt=""></span>
                                Home
                            </a>
                        </li>
                        <li class="profile">
                            <a href="{% url 'profiles:profileView' request.user %}" title="">
                                <span><img src="{% static 'images/icon3.png' %}" alt=""></span>
                                Profile
                            </a>
                        </li>
                        <li class="request">
                            <a href="{% url 'requests:friendRequests' %}" title="">
                                <span><img src="{% static 'images/icon4.png' %}" alt=""></span>
                                Friend Requests
                            </a>
                        </li>
                        <li class="message">
                            <a href="{% url 'message:messages' %}" title="" class="not-box-open">
                                <span><img src="{% static 'images/icon6.png' %}" alt=""></span>
                                Messages
                            </a>
                        </li>
                        <li class="file">
                            <a href="{% url 'message:files'  %}" title="">
                                <span><img src="{% static 'images/icon5.png' %}" alt=""></span>
                                Files
                            </a>
                        </li>
                        <li class="chat">
                            <a href="{% url 'chat:chatRooms'  %}" title="">
                                <span><img src="{% static 'images/chat.png' %}" width="20px" style="margin-top: -10%;" alt=""></span>
                                Chat
                            </a>
                        </li>
                        <li class="groups">
                            <a href="{% url 'groups:groupList' %}" title="">
                                <span><img src="{% static 'images/icon2.png' %}" alt=""></span>
                                Groups
                            </a>
                        </li>
                        <li class="generateSOS">
                            <a href="{% url 'message:generateSOS' %}" title="" class="not-box-open">
                                <span><img src="{% static 'images/icon7.png' %}" alt=""></span>
                                SOS
                            </a>
                        </li>
                        <li class="SOS">
                            <a href="{% url 'message:SOS' %}" title="" class="not-box-open">
                                <span><img src="{% static 'images/icon9.png' %}" alt=""></span>
                                View SOS
                            </a>
                        </li>
                    </ul>
                </nav><!--nav end-->
                <div class="menu-btn">
                    <a href="#" title=""><i class="fa fa-bars"></i></a>
                </div><!--menu-btn end-->


            </div><!--header-data end-->

        {% endblock %}
        </div>
    {% block logout %}
        {% if request.user != 'AnonymousUser' %}
        <a href="{% url 'accounts:logout' %}">
            <div class="nav navbar-nav navbar-right fa fa-sign-out" style="float: right; color: white ; border: 0px;   margin-top: 1%; font-size:24px;"> </div>
         </a>
        {% endif %}
    {% endblock %}
    </header><!--header end-->
.
    <div id="map"></div>
    <script>
      // Note: This example requires that you consent to location sharing when
      // prompted by your browser. If you see the error "The Geolocation service
      // failed.", it means you probably did not give permission for the browser to
      // locate you.
      var map, infoWindow;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -34.397, lng: 150.644},
          zoom: 6
        });
        infoWindow = new google.maps.InfoWindow;

        // Try HTML5 geolocation.
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var pos = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };

            infoWindow.setPosition(pos);
            infoWindow.setContent("{{ member }}");
            infoWindow.open(map);
            map.setCenter(pos);
          }, function() {
            handleLocationError(true, infoWindow, map.getCenter());
          });
        } else {
          // Browser doesn't support Geolocation
          handleLocationError(false, infoWindow, map.getCenter());
        }
      }

      function handleLocationError(browserHasGeolocation, infoWindow, pos) {
        infoWindow.setPosition(pos);
        infoWindow.setContent(browserHasGeolocation ?
                              'Error: The Geolocation service failed.' :
                              'Error: Your browser doesn\'t support geolocation.');
        infoWindow.open(map);
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCD1dTQZSGdJBuAmgbNt6QX1boH930n3CY&callback=initMap">
    </script>
  </body>
</html>

Socio/templates/temp1.html
<!-- CSS -->
<style>
#my_camera{
 width: 320px;
 height: 240px;
 border: 1px solid black;
}
</style>

<!-- -->
 <div id="my_camera"></div>
 <input type=button value="Configure" onClick="configure()">
 <input type=button value="Take Snapshot" onClick="take_snapshot()">
 <input type=button value="Save Snapshot" onClick="saveSnap()">

 <div id="results" ></div>

 <!-- Script -->
 <script type="text/javascript" src="{%  %}"></script>

 <!-- Code to handle taking the snapshot and displaying it locally -->
 <script language="JavaScript">

 // Configure a few settings and attach camera
 function configure(){
  Webcam.set({
   width: 320,
   height: 240,
   image_format: 'jpeg',
   jpeg_quality: 90
  });
  Webcam.attach( '#my_camera' );
 }
 // A button for taking snaps


 // preload shutter audio clip

 function take_snapshot() {
  // take snapshot and get image data
  Webcam.snap( function(data_uri) {
  // display results in page
  console.log(data_uri);
  document.getElementById('results').innerHTML =
   '<img id="imageprev" src="'+data_uri+'"/>';
  } );

  Webcam.reset();
 }

function saveSnap(){
 // Get base64 value from <img id='imageprev'> source
 var base64image = document.getElementById("imageprev").src;

 Webcam.upload( base64image, 'upload.php', function(code, text) {
  console.log('Save successfully');
  //console.log(text);
 });

}
</script>