Socio/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login"),
    path('createFace/', views.createFace, name="createFace"),
    path('createFaceEncoding/', views.createFaceEncoding, name="createFaceEncoding"),
    path('face/', views.face, name="face"),
    path('loginFace/', views.loginFace, name="uploadFace"),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('password-change/', views.PasswordChangeView.as_view(),name='password-change'),
]

Socio/chat/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'chat'

urlpatterns = [
    path('chat/',views.ChatRooms.as_view(),name='chatRooms'),
    path('chat/<pk>',views.chats,name='chats'),
    path('chat/<pk>/location/<id>',views.location,name='location'),
    path('save_message/', views.save_message, name='chat_save_message'),
    path('share_location/', views.share_location, name='chat_share_location'),
]

Socio/groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('groups', views.GroupListView.as_view(), name="groupList"),
    path('groups/create', views.CreateGroupView.as_view(), name="createGroup"),
    path('groups/edit/<pk>', views.UpdateGroupView.as_view(), name="updateGroup"),
    path('groups/delete/<pk>', views.DeleteGroupView.as_view(), name="deleteGroup"),
    path('groups/leave/<pk>', views.leaveGroup, name="leaveGroup"),
    path('groups/members/<pk>', views.addMember, name="members"),
    path('groups/add-member/<pk>', views.AddMemberView.as_view(), name="addMember"),
    path('groups/add-admin/<pk>', views.AddAdminView.as_view(), name="addAdmin"),
    path('groups/<name>',views.GroupView.as_view(),name="groupDetail"),
    path('groups/createPost/<pk>',views.CreatePost.as_view(),name="createPost"),


]

Socio/message/urls.py
from django.urls import path
from . import views

app_name = 'message'

urlpatterns = [
    path('message/create/<username>',views.CreateMessageView.as_view(), name="createMessage"),
    path('message',views.MessagesView.as_view(), name="messages"),
    path('generateSOS',views.SOS, name="generateSOS"),
    path('SOS',views.SOSView.as_view(), name="SOS"),
    path('SOS/location/<pk>', views.location, name='location'),
    path('files', views.FilesView.as_view(), name="files"),
    path('file/<username>',views.FileUploadView.as_view(), name="uploadFile"),
    path('download/<file_name>', views.downloadFile, name="download"),
    path('check/<file_name>', views.checkFile, name="check"),
]

Socio/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('all/profile',views.AllProfilesView.as_view(), name="allProfiles"),
    path('profile/friends', views.friendList, name="friendList"),
    path('profile/friends/<pk>', views.removeFriend, name="removeFriend"),
    path('profile/<username>', views.ProfileView.as_view(), name="profileView"),
    path('profile/edit/<pk>', views.UpdateProfileView.as_view(), name="editProfile"),
    path('profile/create/<pk>', views.CreateProfileView.as_view(), name="createProfile"),

]

Socio/socio/urls.py
from django.contrib import admin
from django.urls import path,include
from posts import views

app_name = 'socio'

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('socio.urls')),
    path('', include('accounts.urls')),
    path('', include('profiles.urls')),
    path('', include('message.urls')),
    path('', include('requests.urls')),
    path('', include('posts.urls')),
    path('', include('chat.urls')),
    path('', include('groups.urls')),
    path('',views.postsView,name='home'),


]

Socio/chat/models.py
from django.db import models
from django.conf import settings
from groups.models import *
User=settings.AUTH_USER_MODEL

class ChatRoom(models.Model):
    eid = models.CharField(max_length=64, unique=True)
    members = models.ManyToManyField(User)
    group = models.OneToOneField(Group, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.eid


class ChatMessage(models.Model):
    room = models.ForeignKey(ChatRoom,on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name="chat_sender",on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now=True, db_index=True)
    text = models.TextField()
    def to_data(self):
        out = {}
        out['id'] = self.id
        out['from'] = self.user
        out['date'] = self.date
        out['text'] = self.text
        return out

Socio/chat/views.py
from django.views import generic
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from .models import *
import json
import threading


# Create your views here.

User = get_user_model()

class ChatRooms(LoginRequiredMixin, generic.ListView):
    login_url = '/login'
    template_name = 'chat/chat-rooms.html'
    context_object_name = 'all_chats'

    def get_queryset(self):
        user = self.request.user
        q = user.chatroom_set.all()
        return q

@login_required(login_url='/login')
def chats(request,pk):
    room = ChatRoom.objects.get(pk=pk)
    if  request.user not in room.members.all():
        return redirect('home')
    cmsgs = ChatMessage.objects.filter(room=room).order_by('-date')[:50]
    msgs = []
    for msg in reversed(cmsgs):
        msgs.append(msg)
    context = {}
    context['room'] = room
    context['messages'] = msgs
    context['user'] = request.user
    return render(request, 'chat/chat_index.html', context)


@login_required(login_url='/login')
def location(request,pk,id):
    room = ChatRoom.objects.get(pk=pk)
    member = User.objects.get(pk=id)
    if request.user not in room.members.all():
        return redirect('home')
    context = {}
    context['room'] = room
    context['member'] = member
    return render(request,"chat/location.html",context)


@csrf_exempt
def save_message(request):
    # if the request method is a POST request
    if request.method == 'POST':
        # content sent via XMLHttpRequests can be accessed in request.body
        # and it comes in a JSON string, that's why we use json library to
        # turn it into a normal dictionary again
        msg_obj = json.loads(request.body.decode('utf-8'))

        # tries to create the message and save it in the db
        msg = ChatMessage()
        msg.room = ChatRoom.objects.get(pk=msg_obj['room'])
        msg.user = User.objects.get(username=msg_obj['user'])
        msg.text = msg_obj['message']
        msg.save()

        return HttpResponse("success")

    else:
        return HttpResponseRedirect('/')

@csrf_exempt
def share_location(request):
    # if the request method is a POST request
    if request.method == 'POST':
        # content sent via XMLHttpRequests can be accessed in request.body
        # and it comes in a JSON string, that's why we use json library to
        # turn it into a normal dictionary again
        return HttpResponse("success")

    else:
        return HttpResponseRedirect('/')

Socio/templates/chat/chat-rooms.html
{%  extends 'base.html' %}
{% load staticfiles %}

{% load thumbnail %}
{% block title %}
Chats
{% endblock %}
{% block extra-head %}
    <script>
        $(document).ready(function () {
            $('.chat').addClass('active');
        })
    </script>
{% endblock %}
{% block body %}
    <div class="container">
    {% if all_chats %}
        <div class="companies-list">
        <div class="row">
            {%  for chat in all_chats %}

                <div class="col-lg-3 col-md-4 col-sm-6 col-12">
                <div class="company_profile_info">
                    <div class="company-up-info">
                        {% if chat.group %}
                            <img src="../{% thumbnail chat.group.picture 140x140 %}" width="100" height="100">
                            <a href="{% url 'groups:groupDetail' chat.group %}"><h3>{{ chat.group.name }} </h3></a>
                            <button class="follow btn"><a href="{% url 'chat:chats' chat.id %}">Chat</a></button>
                        {% else %}
                            {% for m in chat.members.all %}
                            {% if m != request.user %}
                                <img src="../{% thumbnail m.profile.picture 140x140 %}" width="100" height="100">
                                <h3><a href="{% url 'profiles:profileView' m %}">{{ m.profile.firstName }} {{ m.profile.lastName }}</a></h3>
                                <button class="follow btn"><a href="{% url 'chat:chats' chat.id %}">Chat</a></button>

                            {% endif %}
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                </div>

            {%  endfor %}
        </ul>
    {% else %}
        <h3>No Chats</h3>
    {%  endif %}
    </div>
{% endblock %}

Socio/templates/chat/chat_index.html
{%  extends 'base.html' %}
{% load staticfiles %}

{% load thumbnail %}
{% block title %}
Chats
{% endblock %}


{% block body %}
<script src="http://localhost:4000/socket.io/socket.io.js"></script>
.
<div class="container col-sm-offset-2 col-sm-8">
    <div class="con-title mg-3">
        <div class="chat-user-info">
            {% if room.group %}
                <img src="../{% thumbnail room.group.picture 140x140 %}" width="100" height="100">
                <h3>{{ room.group.name }} <span class="status-info"></span></h3>
            {% else %}
                {% for m in room.members.all %}
                {% if request.user != m %}
                    <img src="../{% thumbnail m.profile.picture 140x140 %}" width="50" height="50">
                    <h3>{{ m.profile.firstName }} {{ m.profile.lastName }}</h3>
                {% endif %}
                {% endfor %}
            {% endif %}
            <div class="location" ><img class="float-right" src="{% static 'images/location.png' %}" width="30px" height="30px"></div>

        </div>
    </div>
    <div id="message-list"  data-mcs-theme="dark" style="height:500px;overflow-y:scroll;width:100%;">
        {% for message in messages %}
            {% if message.user == request.user %}
            <div class="text-right chat-msg">
                <p>{{ message.text }}</p>
                <span>{{ message.date.time }}</span>
            </div>
            {% else %}
            <div class="chat-msg st2">

                <p><span>{{ message.user }}</span>{{ message.text }}</p>
                <span>{{ message.date.time }}</span>
            </div>
            {% endif %}
        {% endfor %}
    </div><!--chat-list end-->
    <div class="typing-msg">
        <form>
            <textarea id="message" placeholder="Type a message here"></textarea>
            <button type="submit"><i class="fa fa-send"></i></button>
        </form>
    </div><!--typing-msg end-->
</div>

<script>

    // host of the server
    var host = 'localhost';
    var port = '4000';

    var socket = io(host + ':' + port);

    // when the document is ready, scrolls down the page to the last page if there are messages
    $(function() {
        updateScroll();
    });

    $('.chat').addClass('active');
    var user = "{{ request.user }}";
    // on the form submit
    $('form').submit(function() {
        // gets the elements by ids
        var url = {% url 'chat:chat_save_message' %}
        var msg = $('#message');
        var room = {{ room.id }};
        // if the message and the name aren't empty or aren't spaces,
        if(msg.val() !== "" && user !== "") {
            // creates the message object
            msgObject = {
                'room': room,
                'user': user,
                'message': msg.val(),
                'date': new Date(),
            };

            // emits the msgObject to the server
            socket.emit('message', msgObject);
        }

        // clear the message element
        msg.val('');
        // returns false to avoid the form to reload the page
        return false;
    });

    $(".location").click(function () {
        console.log('location');
       var msg = "{{ request.user }} shared his location";
       var url = '{% url "chat:location" room.pk request.user.pk %}' ;
        var room = {{ room.id }};
        // if the message and the name aren't empty or aren't spaces,
            // creates the message object
            msgObject = {
                'room': room,
                'user': user,
                'message': msg,
                'url':url,
                'date': new Date(),
            };

            // emits the msgObject to the server
            socket.emit('location', msgObject);
        return false;
    });

    // receives the message object from the server
    socket.on('getMessage', function(msgObject) {
        // gets the fields of the message
        var name = msgObject.user;
        var msg = msgObject.message;
        var date = new Date(msgObject.date);
        var room = msgObject.room;
        time = dateFormat(date, " h:MM tt");
        if(room == {{ room.id }}) {
            if (name != user) {
                new_message = '<div class="chat-msg st2">' + '<p><span >' + name + ':</span>&emsp;' + msg + '</p><span>' + time + '</span>' + '</div>'
                // appends the message to the screen
            }
            else {
                new_message = '<div class="text-right chat-msg"><p>' + msg + '</p><span>' + time + '</span></div>'
            }
            $('#message-list').append(new_message);
            console.log(document.getElementById("message-list"));
        }
        // updates the scroll
        updateScroll();
    });

    socket.on('getLocation', function(msgObject) {
        // gets the fields of the message
        var name = msgObject.user;
        var msg = msgObject.message;
        var url = msgObject.url;
        var date = new Date(msgObject.date);
        var room = msgObject.room;
        time = dateFormat(date, " h:MM tt");
        if(room == {{ room.id }}) {
            if (name != user) {
                new_message = '<a href='+url+'><div class="chat-msg st2">' + '<p><span >' + name + ':</span>&emsp;' + msg + '</p><span>' + time + '</span>' + '</div></a>'
                // appends the message to the screen
            }
            else {
                new_message = '<a href='+url+'><div class="text-right chat-msg"><p>' + msg + '</p><span>' + time + '</span></div></a>'
            }
            $('#message-list').append(new_message);
        }
        {#// updates the scroll#}
        updateScroll();
    });

    function updateScroll(){
        var element = document.getElementById("message-list");
        element.scrollTop = element.scrollHeight;
    }
</script>

{% endblock %}

Socio/templates/chat/chats.html
{%  extends 'base.html' %}
{% load staticfiles %}

{% load thumbnail %}
{% block title %}
Chats
{% endblock %}
{% block body %}
    <div id="chat-log" class="container fa-border">
      {% for msg in messages %}
          {% if msg.from == request.user %}
              <div class="col-sm-offset-4 col-sm-8">
                  <p class="fa-border text-right" style="word-wrap: break-word">{{ msg.text }}&emsp;
                  <sub style="font-size: xx-small">{{ msg.date.time }}</sub></p>
              </div><br>
          {% else %}
              <div class="fa-border col-sm-8">
              <p class=""><b>{{ msg.from }}</b>:<span style="word-wrap: break-word;"> {{ msg.text }}&emsp;</span>
                  <sub style="font-size: xx-small">{{ msg.date.time }}</sub></p>
              </div><br>
          {% endif %}
      {% endfor %}
    </div>
    <br>
    <div class="container">
    <form class="chat-form" action="{% url 'chat:chatMessage' room_id %}" style="display: flex">
        {% csrf_token %}
        <input type="text" class="chat-msg">
        <button class="btn btn-sm btn-info submit-msg" type="submit">Send</button>
    </form>
    </div>
{% endblock %}

{% block extra-head %}
    <script>
    $(document).ready(function () {
        $('.chat').addClass('active');
        $('.submit-msg').click(function (e) {
            e.preventDefault();
            var Url = $('.chat-form').attr('action');
            var text = $('.chat-msg').val();
            var user = {{ request.user.pk }};
            $.ajax({
                url: Url,
                method: "GET",
                data:{
                    'user_id': user,
                    'text': text,
                },
                success: function (data) {
                    $('.chat-msg').val('');
                }, error: function (error) {
                    console.log(error);
                }
            });
        })
    });
    </script>
{% endblock %}

Socio/templates/chat/location.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <title>Geolocation</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/line-awesome.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/line-awesome-font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/slick.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/slick-theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}">
    <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'js/dateFormat.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.mCustomScrollbar.js' %}"></script>
    <script type="text/javascript" src="{% static 'lib/slick.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/scrollbar.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
  </head>
  <body>
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
        <header id="header">
        <div class="container">
            {% block navbar %}
            <div class="header-data">
                <div class="logo">
                    <a href="{% url 'home' %}" title=""><img src="{% static 'images/logo.png' %}" width="40px" height="40px" alt=""></a>
                </div><!--logo end-->
                <div class="search-bar">
                    <form  class="navbar-form navbar-left" role="search" method="get" action="{% url 'profiles:allProfiles' %}">
                        <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                        <button type="submit"><i class="la la-search"></i></button>
                    </form>
                </div><!--search-bar end-->
                <nav>
                    <ul>
                        <li class="home">
                            <a href="{% url 'home' %}" title="">
                                <span><img src="{% static 'images/icon1.png' %}" alt=""></span>
                                Home
                            </a>
                        </li>
                        <li class="profile">
                            <a href="{% url 'profiles:profileView' request.user %}" title="">
                                <span><img src="{% static 'images/icon3.png' %}" alt=""></span>
                                Profile
                            </a>
                        </li>
                        <li class="request">
                            <a href="{% url 'requests:friendRequests' %}" title="">
                                <span><img src="{% static 'images/icon4.png' %}" alt=""></span>
                                Friend Requests
                            </a>
                        </li>
                        <li class="message">
                            <a href="{% url 'message:messages' %}" title="" class="not-box-open">
                                <span><img src="{% static 'images/icon6.png' %}" alt=""></span>
                                Messages
                            </a>
                        </li>
                        <li class="file">
                            <a href="{% url 'message:files'  %}" title="">
                                <span><img src="{% static 'images/icon5.png' %}" alt=""></span>
                                Files
                            </a>
                        </li>
                        <li class="chat">
                            <a href="{% url 'chat:chatRooms'  %}" title="">
                                <span><img src="{% static 'images/chat.png' %}" width="20px" style="margin-top: -10%;" alt=""></span>
                                Chat
                            </a>
                        </li>
                        <li class="groups">
                            <a href="{% url 'groups:groupList' %}" title="">
                                <span><img src="{% static 'images/icon2.png' %}" alt=""></span>
                                Groups
                            </a>
                        </li>
                        <li class="generateSOS">
                            <a href="{% url 'message:generateSOS' %}" title="" class="not-box-open">
                                <span><img src="{% static 'images/icon7.png' %}" alt=""></span>
                                SOS
                            </a>
                        </li>
                        <li class="SOS">
                            <a href="{% url 'message:SOS' %}" title="" class="not-box-open">
                                <span><img src="{% static 'images/icon9.png' %}" alt=""></span>
                                View SOS
                            </a>
                        </li>
                    </ul>
                </nav><!--nav end-->
                <button class="follow btn" style="margin-top: 1%;"><a href="{% url 'chat:chats' room.id %}" class="not-box-open">
                    Back to chat
                </a></button>
                <div class="menu-btn">
                    <a href="#" title=""><i class="fa fa-bars"></i></a>
                </div><!--menu-btn end-->


            </div><!--header-data end-->

        {% endblock %}
        </div>
    {% block logout %}
        {% if request.user != 'AnonymousUser' %}
        <a href="{% url 'accounts:logout' %}">
            <div class="nav navbar-nav navbar-right fa fa-sign-out" style="float: right; color: white ; border: 0px;   margin-top: 1%; font-size:24px;"> </div>
         </a>
        {% endif %}
    {% endblock %}
    </header><!--header end-->


    .
    <div id="map"></div>
    <script>
      // Note: This example requires that you consent to location sharing when
      // prompted by your browser. If you see the error "The Geolocation service
      // failed.", it means you probably did not give permission for the browser to
      // locate you.
      var map, infoWindow;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -34.397, lng: 150.644},
          zoom: 6
        });
        infoWindow = new google.maps.InfoWindow;

        // Try HTML5 geolocation.
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var pos = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };

            infoWindow.setPosition(pos);
            infoWindow.setContent("{{ member }}");
            infoWindow.open(map);
            map.setCenter(pos);
          }, function() {
            handleLocationError(true, infoWindow, map.getCenter());
          });
        } else {
          // Browser doesn't support Geolocation
          handleLocationError(false, infoWindow, map.getCenter());
        }
      }

      function handleLocationError(browserHasGeolocation, infoWindow, pos) {
        infoWindow.setPosition(pos);
        infoWindow.setContent(browserHasGeolocation ?
                              'Error: The Geolocation service failed.' :
                              'Error: Your browser doesn\'t support geolocation.');
        infoWindow.open(map);
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCD1dTQZSGdJBuAmgbNt6QX1boH930n3CY&callback=initMap">
    </script>
  </body>
</html>